### ISSUE TITLE
How to know that a create node operation is finished?

### ISSUE THREAD

**Issue by tompe17** [blumenthal/ubx_robotscenegraph#16]
The documentation talks about json_in_port.  In the usc file a json_out_port is mentioned. How is the out port used?

I have problem using the json interface. I create a node and directly after I ask for the id of the node but the node is not created yet. So how do I synchronize that? What is the feedback for a create request? The documentation have code doing sleep(1) but that is not acceptable since then it will take to long time to do operations like updating the GeoPose.

**Comment by blumenthal** [comment]
This is a very valid point. The problem here is that the PUB-SUB mechanism does not send back an acknowledgement. Even worse, ZMQ does not guarantee that the first message that is send actually arrives. The idea behind the PUB-SUB interface is to continuously update e.g. a geopose of a robot.

I made a revision of the interface [1]. Now it is possible to (a) use the PUB-SUB channel for stream like updates or (b) the REQ-REP server that already exists for queries also. It will return an indication if an update update was applied correctly. The message format for sending the update is exactly the same as before. 

Example for the new interface:

```
python get.py new_node.json 
Sending query: {
  "@worldmodeltype": "RSGUpdate",
  "operation": "CREATE",
  "node": {
    "@graphtype": "Node",
    "id": "92cf7a8d-4529-4abd-b174-5fabbdd3068f", 
    "attributes": [
          {"key": "name", "value": "myNode"},
          {"key": "comment", "value": "Some human readable comment on the node."}
    ],
  },
  "parentId": "e379121f-06c6-4e21-ae9d-ae78ec1986a1",
}
```

The reply is:

```
{"@worldmodeltype": "RSGUpdateResult","updateSuccess": true} 
```

on success or 

```
{"@worldmodeltype": "RSGUpdateResult","updateSuccess": false} 

```

on failure.

To test the same update with the PUB-SUB use: `python add_node.py` 

[1] https://github.com/brics/brics_3d/commit/4ea52693b3ac2f783f019a7acdaf661f3da69b06
